include: package:very_good_analysis/analysis_options.2.4.0.yaml
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    library_private_types_in_public_api: false
    one_member_abstracts: false
    annotate_overrides: false
    overridden_fields: false
    avoid_dynamic_calls: false
analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated_plugin_registrant.dart"
    - "lib/l10n/l10n.dart"
    - "lib/features/dashboard/presentation/widgets/curve_container.dart"
    - "lib/core/injections/locator.config.dart"
    - "test/**"
